graph TD
    subgraph HOST_MACHINE [Máy tính của bạn]
        Producer_Script[Python Producer Script]
        Browser[Trình duyệt Web]
    end

    subgraph DOCKER_NETWORK [Mạng nội bộ Docker]
        direction TB
        
        Kafka[Kafka Service]
        SparkM[Spark Master]
        SparkW[Spark Worker]
        Postgres[(Postgres DB)]
        Redis[(Redis Cache)]
        Metabase[Metabase UI]

        %% Kafka Connections
        Producer_Script -- "localhost:9092" --> Kafka
        SparkW -- "kafka:29092" --> Kafka

        %% Spark Internal
        SparkW -- "spark-master:7077" --> SparkM
        
        %% Spark Outputs
        SparkW -- "Port 5432" --> Postgres
        SparkW -- "Port 6379" --> Redis

        %% Metabase Connections
        Metabase -- "Lưu config (Port 5432)" --> Postgres
        Metabase -- "Đọc dữ liệu hiển thị" --> Postgres
    end

    %% Web UI Access
    Browser -- "localhost:8080" --> SparkM
    Browser -- "localhost:3000" --> Metabase